name: "Code Captains"
description: "Determines which Code Captains are required to review a PR"

inputs:
    changed-files:
        description: Paths of the changed files, delimited by |
        required: true
    token:
        description: GitHub token used to fetch PR approvers and team members from Github's API
        required: true
        default: ${{ github.token }}

runs:
    using: node20
    main: ./packages/code-captains-github-action/dist/index.js

branding:
    icon: users
    color: white
