packages:
    - packages/*
catalog:
    "@types/node": ^20.11.20
    eslint: ^8.0.0
    eslint-config-goldilocks: ^1.0.0
    prettier: ^3.0.0
    typescript: 5.3.2
    vitest: ^2.0.0
    zod: ^3.23.8
