name: Code Captains

on:
    workflow_call:

jobs:
    code-captains:
        permissions:
            contents: read
            pull-requests: write

        runs-on: ubuntu-latest

        steps:
            - name: Checkout all code-captains.yml files on target branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.base_ref }}
                  sparse-checkout: code-captains.yml
                  sparse-checkout-cone-mode: false

            - name: Determine changed files
              id: changed-files
              uses: tj-actions/changed-files@v45
              with:
                  json: true

            - name: Determine Code Captains
              id: code-captains
              uses: upshift-dev/code-captains@0.1.0
              with:
                  changed-files: ${{ steps.changed-files.outputs.all_changed_files }}

            - name: Find Code Captains comment
              uses: peter-evans/find-comment@v3
              id: find-comment
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: "github-actions[bot]"
                  body-includes: Code Captains

            - name: Record Code Captains on comment
              if: ${{ steps.code-captains.outputs.code-captains != '' }}
              uses: peter-evans/create-or-update-comment@v4
              with:
                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      Determined the following Code Captains:
                      ${{ steps.code-captains.outputs.code-captains }}

                      This PR includes changes that matched these policies:
                      ${{ steps.code-captains.outputs.met-policy-files }}
                  edit-mode: replace

            - name: Record empty Code Captains comment
              if: ${{ steps.code-captains.outputs.code-captains == '' }}
              uses: peter-evans/create-or-update-comment@v4
              with:
                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: No Code Captains are applicable to this PR.
                  edit-mode: replace
