name: Build and Test

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - uses: actions/checkout@v4.1.6
            - uses: pnpm/action-setup@v4
            - run: pnpm install
            - run: pnpm run -r build
            - name: Check if build modified files
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                  echo "Build resulted in changes!"
                  exit 1
                  fi

    test-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - uses: actions/checkout@v4.1.6
            - uses: pnpm/action-setup@v4
            - run: pnpm install
            - run: pnpm run test

    test-reusable-workflow:
        uses: ./.github/workflows/code-captains-workflow.yml
