name: Build and Test

on:
    pull_request:

jobs:
    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/setup-node@v4
    #           with:
    #               node-version: 20.x
    #         - uses: actions/checkout@v4.1.6
    #         - uses: pnpm/action-setup@v4
    #         - run: pnpm install
    #         - run: pnpm run -r build

    test-reusable-workflow:
        uses: ./.github/workflows/code-captains.yml
